server:
  port: 8081
  

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
  
routing-service:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 1000   
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka


spring:
  application:
    name: booking-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
    stream:
      bindings:
        cargoBookingChannel:
          destination: cargoBookings          
          binder: rabbit
        cargoRoutingChannel:
          destination: cargoRoutings         
          binder: rabbit
        cargoHandlingChannel:
          destination: cargoHandling
          group: cargoHandlingInBookingQueue
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
   
                
                
                
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console